mybatis-plus:
  configuration:
    # 自动映射枚举类型
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    # 开启下划线转驼峰命名
    map-underscore-to-camel-case: true
    # 开启SQL日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  application:
    name: lowCode-workflow-framework-graph

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lowcode_kernel_flow?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yy3908533
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20


# 设置日志级别为debug
logging:
  level:
    com.lowcode.workflow.runner.graph: debug